# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 05:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaffInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='name')),
                ('code', models.CharField(max_length=80, verbose_name='code')),
                ('email', models.TextField(verbose_name='email')),
                ('join_date', models.DateTimeField(auto_now_add=True, verbose_name='join_date')),
            ],
            options={
                'ordering': ('join_date',),
            },
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='name')),
                ('description', models.TextField()),
                ('create_user', models.CharField(blank=True, max_length=80, verbose_name='create_user')),
                ('join_date', models.DateTimeField(auto_now_add=True, verbose_name='join_date')),
            ],
            options={
                'ordering': ('join_date',),
            },
        ),
        migrations.AddField(
            model_name='staffinfo',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staffs', to='metricBA_apps.UserGroup'),
        ),
        migrations.AlterUniqueTogether(
            name='staffinfo',
            unique_together=set([('name', 'code', 'group')]),
        ),
    ]
